name: covid19cuba
description: Mobile application of Covid19 Cuba Data project implemented with Flutter.

version: 1.0.0+14

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  shared_preferences: ^0.5.7
  preferences: ^5.2.0
  charts_flutter: ^0.9.0
  http: ^0.12.0+4
  getflutter: ^1.0.11
  flutter_launcher_icons: ^0.7.5
  url_launcher: ^5.4.5
  flutter_local_notifications: ^1.4.2
  background_fetch: ^0.5.5
  package_info: ^0.4.0+17
  introduction_screen: ^1.0.8
  json_annotation: ^3.0.1
  font_awesome_flutter: ^8.8.1
  share: ^0.6.4
  demoji: ^1.0.1
  crypto: ^2.1.4
  country_pickers: ^1.2.1
  flutter_linkify: ^3.1.2
  searchable_dropdown: ^1.1.3
  timezone: ^0.5.7
  flutter_html: ^0.11.1
  flutter_svg: ^0.17.4
  flutter_custom_clippers: ^1.1.1
  search_choices: ^1.0.15
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  grizzly_io: ^2.2.0
  pdf: ^1.8.0
  device_info: ">=0.4.2+4 <2.0.0"
  badges: ^1.1.1
  simple_autocomplete_formfield: ^0.2.7
  quiver: ^2.1.3
  random_color:
    path: ./RandomColor
  flutter_echarts:
    path: ./flutter_echarts
  webview_flutter:
    path: ./webview_flutter
  fluttercontactpicker: ^2.4.2

dev_dependencies:
  flutter_native_splash: ^0.1.9
  json_serializable: ^3.3.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - flutter_echarts/assets/echart.html
    - assets/images/
    - assets/images/carousel/
    - assets/js/leaflet.js
    - assets/js/jquery.min.js
    - assets/js/map.js
    - assets/js/bootstrap.min.js
    - assets/css/bootstrap.min.css
    - assets/css/custom.css
    - assets/css/leaflet.css
    - assets/provincias.geojson
    - assets/municipios.geojson
    - assets/js/geojsondata.js
    - assets/map.html
    - assets/map2.html
    - assets/js/municipios.js
    - assets/data/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
    - family: CubaIcon
      fonts:
        - asset: fonts/CubaIcon.ttf

flutter_native_splash:
  image: assets/images/icon.jpg
  color: "1c1340"
